### ISSUE TITLE
release of chart for console 1.27

### ISSUE THREAD

**Issue by mcpheesvoz** [conduktor/conduktor-public-charts#110]
I can see you've recently done an MR for the new version of console -- at what point does this get created as a new release of the chart? `1.11.0` is still the latest chart, which is console `1.26` ... I'd like to update my non-prod install asap with the new version to test out the new features.
thanks!
scot

**Comment by qboileau** [comment]
Hi, @mcpheesvoz 
I've just published the [1.12.0](https://github.com/conduktor/conduktor-public-charts/releases/tag/console-1.12.0) of console helm chart that contain 1.27.0 release of console. 
Thanks for the reminder and enjoy our latest update :wink:
