### ISSUE TITLE
Chart not found

### ISSUE THREAD

**Issue by Jojoooo1** [conduktor/conduktor-public-charts#4]
It seems the chart are not available within chart repo.

Error: chart "console" version "1.0.0" not found in https://helm.conduktor.io repository 
Error: chart "console" version "1.0.1" not found in https://helm.conduktor.io repository

**Comment by qboileau** [comment]
Hi @Jojoooo1 thanks for the report. 

We had an issue that broke Helm index. 

It should be fixed now please update your repo `helm repo update` before re-testing
