### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by WDaan** [conduktor/conduktor-public-charts#74]
Hi!

This projects looks great so far. It's great that you're able to self-host it and that the free version is more than capable.
Is there a plan to add a License to the image and the Helm Charts? This is currently the only thing blocking us from using it.

Thanks!

**Comment by sderosiaux** [comment]
Hi @WDaan, thanks for your message. We've added an Apache 2 license to this Helm repo.

Don't hesitate if you have any question
