### ISSUE TITLE
help when I use console-cortex:2.6.0 Please set it in the config file or in the environment variable CDK_DATABASE_URL

### ISSUE THREAD

**Issue by wfy-belief** [conduktor/conduktor-public-charts#99]
![image](https://github.com/user-attachments/assets/62313cba-a01e-421c-97a4-23f66ffe1bd3)

 Please set it in the config file or in the environment variable CDK_DATABASE_URL
 
 but in doc is not necessary
 
 when I change the tag to 2.5.1， it is ok
 
 
![image](https://github.com/user-attachments/assets/9a45edcb-d85a-47f0-99e9-b3dd2c6a3222)

I only changed the image tag

**Comment by qboileau** [comment]
Hi @wfy-belief, 

your first screenshot show `conduktor-console` container logs  and not `conduktor-console-cortex` one. 

Only `conduktor-console` container require database connection using `config.database.*` values (see chart [README](https://github.com/conduktor/conduktor-public-charts/blob/main/charts/console/README.md) for examples). 
If set from `config.database.*` values, the chart will create a configuration file inside a ConfigMap that is used by console container as startup configuration. 
It can still be possible to specify manually an env var `CDK_DATABASE_URL` but it's not recommended when using the Helm Chart.

`conduktor-console-cortex` don't need a database but can use an external object storage for production setup. You can find more configuration details on `conduktor-console-cortex` image under [`monitoringConfig`](https://github.com/conduktor/conduktor-public-charts/blob/main/charts/console/README.md#platform-monitoring-product-parameters) values.

Also, not that we just publish a [new version 1.11.0 of the chart](https://github.com/conduktor/conduktor-public-charts/releases/tag/console-1.11.0) with  `conduktor-console`  and `conduktor-console-cortex`  updated to latest release `1.26.0`. We also fix a probe issue when configuring TLS on Console. But we didn't find any issue with database configuration. 

Hope this help. If you still have issue, can you paste your values.yaml to help us debug.

**Comment by wfy-belief** [comment]
@qboileau thank you，I'm just checking the configuration. I think there's something wrong with my configuration
